# Generated by Django 4.2.29 on 2026-03-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Depoimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_dono", models.CharField(max_length=100)),
                ("nome_pet", models.CharField(max_length=100)),
                ("texto", models.TextField()),
                ("foto_pet", models.ImageField(upload_to="depoimentos/")),
            ],
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "icone",
                    models.CharField(
                        help_text="Nome do ícone Bootstrap (ex: bi-scissors)",
                        max_length=50,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
    ]
