# Generated by Django 4.2.29 on 2026-03-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petshop", "0002_categoria_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="destaque",
            field=models.BooleanField(
                default=False, help_text="Aparecer na página inicial?"
            ),
        ),
    ]
