# Generated by Django 4.2.29 on 2026-03-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petshop", "0003_produto_destaque"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="selo_oferta",
            field=models.BooleanField(
                default=False, help_text="Mostrar selo de Oferta?"
            ),
        ),
    ]
