# Generated by Django 4.2.29 on 2026-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petshop", "0004_produto_selo_oferta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Galeria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=100)),
                ("imagem", models.ImageField(upload_to="galeria/")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Galeria de Fotos",
            },
        ),
    ]
